name: Update Action

permissions:
  contents: write

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Input the version update the repo to (e.g., 1.0.0)'
                required: true
    repository_dispatch:
        types: [update]
        

jobs:
  update-generated-files-and-release:
    env:
        VERSION: ${{ github.event.inputs.version || github.event.client_payload.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace generated files with new version
        run: |
          VERSION=${{ env.VERSION }}
          echo "Updating generated files to version $VERSION"
          for f in gen/*; do
            sed "s/\$VERSION$/$VERSION/" $f > $(basename $f)
          done

      - name: Commit, push  and tag changes
        run: |
          VERSION=${{ env.VERSION }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update generated files to version $VERSION"
          git push origin main
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Updated generated files to version ${{ env.VERSION }}.
          draft: true
          prerelease: false
          
      
      
      